config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  as :user do
    get "sign_in" => "devise/sessions#new"
    get "sign_up" => "devise/registrations#new"
    delete "sign_out" => "devise/sessions#destroy"
    get "edit_user" => "devise/registrations#edit"
  end
  # get 'pages/home'
  # Dfine your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"

  # get 'pages/about'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <title>Return Rails Website App</title>
  </head>
  <body>
    <!-- Header NAVBAR -->
    <%= render "partials/header" %>
    <article>
      <!-- Flash message -->
      <%
=begin%>
 <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p> 
<%
=end%>
      <% flash.each do |name, message| %>
        <%= content_tag(:div, message, class: "alert alert-info #{name}") %>
      <% end %>

      <div>
        <%= yield %>
      </div>
    </article>
    <!-- Footer -->
    <%= render "partials/footer" %>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS, fontawesome -->
    <script src="https://kit.fontawesome.com/f63cc4ee37.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    </body>
</html>

app/views/pages/about.html.erb
<div class="bg-light pt-3 pb-3 mb-3">
    <div class="container">
        <h1> Welcome to Aboutpage </h1>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>
        <%= link_to "More...", "#", class: "btn btn-primary btn-sm" %>
    </div>
</div>

app/views/pages/contact.html.erb
<div class="bg-light pt-3 pb-3 mb-3">
    <div class="container">
        <h1> Welcome to Contact page </h1>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>
        <%= link_to "Send email", "#", class: "btn btn-primary btn-sm" %>
    </div>
</div>

app/views/pages/home.html.erb
<div class="bg-light jumbotron-home pt-3 pb-3 mb-3">
    <% if user_signed_in? %>
        <div class="container">
            <h1> Welcome, stranger! </h1>
            <%= link_to "Edit myself", edit_user_path, class: "btn btn-primary btn-sm" %>
        </div>
    <% else %>
        <div class="container">
            <h1> Welcome, stranger! </h1>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>
            <%= link_to "Learn more...", "#", class: "btn btn-primary btn-sm" %>
        </div>
    <% end %>
</div>
<div class="container">
    <div class="row mb-3">
        <div class="col-md-4">
            <h3> Heading </h3>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>
            <%= link_to "View detail", "#", class: "btn btn-outline-success btn-sm" %>
        </div>
        <div class="col-md-4">
            <h3> Heading </h3>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>
            <%= link_to "View detail", "#", class: "btn btn-outline-success btn-sm" %>
        </div>
        <div class="col-md-4">
            <h3> Heading </h3>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>
            <%= link_to "View detail", "#", class: "btn btn-outline-success btn-sm" %>
        </div>
    </div>
</div>

app/views/partials/_footer.html.erb
<footer class="text-center text-white bg-dark">
    <div class="container p-4 pb-0">
        <section class="mb-4">
            <%= link_to "https://www.facebook.com/", class: "btn btn-outline-light btn-floating m-1" do %>
                <i class="fab fa-facebook-f"></i>
            <% end %>
            <%= link_to "https://mail.google.com/", class: "btn btn-outline-light btn-floating m-1" do %>
                <i class="fa fa-envelope"></i>
            <% end %>
            <%= link_to "https://www.linkedin.com/", class: "btn btn-outline-light btn-floating m-1" do %>
                <i class="fab fa-linkedin-in"></i>
            <% end %>
            <%= link_to "https://github.com/", class: "btn btn-outline-light btn-floating m-1" do %>
                <i class="fab fa-github"></i>
            <% end %>
        </section>
    </div>
    <div class="p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2020 Copyright:
        <a class="text-white" href="#">NgocPHV</a>
    </div>
</footer>

app/views/partials/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark" aria-label="Third navbar example">
    <div class="container-fluid">
      <%= link_to "Rails", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-header" aria-controls="navbar-header" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbar-header">
        <ul class="navbar-nav me-auto mb-2 mb-sm-0">
          <li class="nav-item">
            <%= link_to "About", about_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", contact_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <form>
              <input class="form-control" type="text" placeholder="Search" aria-label="Search">
            </form>
          </li>
        </ul>
        <ul class="navbar-nav">
          <% if !user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Sign-in", sign_in_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign-up", sign_up_path, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign-out", sign_out_path, data: {"turbo-method": :delete, turbo_confirm: "Are you want to logout?"}, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
</nav> 